### ISSUE TITLE
Memory Leak on NewFromMemory function

### ISSUE THREAD

**Issue by agentabstract** [gen2brain/go-fitz#26]
In the NewFromMemory function you read the byte slice into a  data variable (*C.uchar) and then turn it into a stream.  When the job is done that variable lingers in memory. I don't know a lot about C or Cgo integration, but I fixed it in my fork of go-fitz by putting the pointer into the document struct and made sure it got freed in the document close method.  When I tried to defer its deletion inside the NewFromMemory function I ran into a panic on the stream.     

To test the problem I read a pdf into a byte slice and had a for loop open it with NewFromMemory, dump its text, and then close the document.  You'll see the build up in ram immediately.  

I figure you might have a better solution than I came up with, because I'm literally guessing at the C commands! ;)

**Comment by gen2brain** [comment]
It should be fixed in https://github.com/gen2brain/go-fitz/commit/f0a07eb939095168e46411b711d98417b8bc37ad, thanks for reporting.

**Comment by jgalat** [comment]
Hi @gen2brain
The issue seems to be still present on f0a07eb. We updated our platform which does a bunch of `NewFromMemory` calls to that last commit and we still are experiencing a leak. Memory is not been freed after a `.Close()` call.

**Comment by agentabstract** [comment]
> Hi @gen2brain
> The issue seems to be still present on [f0a07eb](https://github.com/gen2brain/go-fitz/commit/f0a07eb939095168e46411b711d98417b8bc37ad). We updated our platform which does a bunch of `NewFromMemory` calls to that last commit and we still are experiencing a leak. Memory is not been freed after a `.Close()` call.

For the record, I never tested this fix.  I'm still using my weird rigged version.  This was a bug that came up in an older project of mine, and I had to slap a fix on it and get back to what I was doing.

**Comment by jgalat** [comment]
According to the docs in MuPDF
![image](https://user-images.githubusercontent.com/9066191/116144420-b4a47b80-a6b2-11eb-8182-b2ff36661b39.png)
ownership of `*data` is not passed in. So the wrapper should be in charge of freeing that allocated memory.
I tested your fix @agentabstract and it's working pretty well. Thanks

**Comment by gen2brain** [comment]
This should be fixed now.

**Comment by matthewbordas** [comment]
@gen2brain this is still a problem. We've fixed it in [our fork](https://github.com/jgalat/go-fitz/commit/e51ae2b4922a8435d61dbb326873fede418f5ec6). Will open a PR
